apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: pg-test
  namespace: test-stateful
spec:
  clusterIP: None
  selector:
    app: pg-test
  ports:
  - port: 5432
    targetPort: 5432
=======
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
>>>>>>> 509fdb843dc0b4d7675f7f83203ebfb01c0dadda
