apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-prod01
  namespace: openshift-gitops
spec:
  destination:
    namespace: nginx-prod01
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize-demo/overlays/prod01
    repoURL: https://github.com/hari7022/gitops-nginx-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

